#!/bin/bash

[[ -z "$SHTOOLS_DIR" || -z "$1" ]] &&\
   exit 0

for type in "$@"
do
    rc_file="$SHTOOLS_DIR/bashrc/.bashrc.$type"
    [[ -f "$rc_file" ]] \
        || exit 0
    touch /root/.bashrc &&\
        cat $rc_file >> /root/.bashrc
done

