#!/bin/bash

type=$1
[[ -z "$SHTOOLS_DIR" || -z "$type" ]] &&\
   exit 0

rc_file="$SHTOOLS_DIR/bashrc/.bashrc.opt.$type"
! [[ -f "$rc_file" ]] &&\
  exit 0

touch /root/.bashrc &&\
    cat $rc_file >> /root/.bashrc
