#!/bin/bash

CVETEST_VERSION=${CVETEST_VERSION:-'0.1.1'}
DOWNLOAD_DIR=$1
TEST_LIST_ITEM=$2

#[[ -z $TEST_LIST_ITEM ]] &&\
#    printf"\nDownload directory or test list not specified. Exiting...\n"
#    exit 1

SCRIPT_DIR=$(dirname "$0")
PATH=$SCRIPT_DIR:$PATH

fnames_array=()
for f in "${@:2}"
do
    fnames_array+=( "test-$f-cve" )
done

curl-github carbon108/cve-test "$CVETEST_VERSION" "$DOWNLOAD_DIR" "${fnames_array[@]}"
