#!/bin/bash

TINI_VERSION=${TINI_VERSION:-'v0.18.0'}
SCRIPT_DIR=$(dirname "$0")
TINI_PATH=${1:-"$SCRIPT_DIR"}

PATH=$SCRIPT_DIR:$PATH

url=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
tini_file="$TINI_PATH/tini"

cmd-exists curl || exit 1

! curl-exists "$url"  &&\
    printf "\e[31m\ntini release \e[0m$TINI_VERSION\e[31m not found\n\e[0m" &&\
    exit 1

mkdir -p $TINI_PATH &&\
    curl -L# $url --output $tini_file &&\
    chmod +x $tini_file
