#!/bin/sh

TINI_VERSION=${TINI_VERSION:-'v0.18.0'}
SCRIPT_DIR=$(dirname "$0")
TINI_PATH=${1:-"$SCRIPT_DIR"}

PATH=$SCRIPT_DIR:$PATH

url=https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini
tini_file="$TINI_PATH/tini"

! curl-exists "$url"  &&\
    printf "\ntini release '$tini_ver' not found\n" &&\
    exit 1

mkdir -p $TINI_PATH &&\
    curl -L# $url --output $tini_file &&\
    chmod +x $tini_file
