#!/bin/bash

SHTOOLS_VERSION=${1:-0.1.7}
SHTOOLS_DIR=${2:-/opt/sh-tools}

sh_tools_url=https://github.com/carbon108/sh-tools-docker/archive/$SHTOOLS_VERSION.zip

tmp_dir=/tmp/carbon108-sh-tools-182WJHDCJH74647-installer
sh_tools_zip=$tmp_dir/sh-tools-$SHTOOLS_VERSION.zip

saved_dir=$PWD

cmd-exists curl || exit 1
cmd-exists unzip || exit 1
cmd-exists shopt || exit 1

mkdir -p "$SHTOOLS_DIR" || exit 1
mkdir -p "$tmp_dir"

curl -L# $sh_tools_url --output $sh_tools_zip &&\
    unzip -o -q $sh_tools_zip -d "$tmp_dir"
cd $tmp_dir/sh-tools-$SHTOOLS_VERSION || exit 1

shopt -s extglob
cp !(tests|install-sh-tools) $SHTOOLS_DIR
    # should omit non-production files
shopt -u extglob

rm -rf $tmp_dir
cd $saved_dir || exit 1