#!/bin/bash

SHTOOLS_VERSION=${1:-0.1.5}
SHTOOLS_DIR=${2:-/opt/sh-tools}

sh_tools_url=https://github.com/carbon108/sh-tools-docker/archive/$SHTOOLS_VERSION.zip

tmp_dir=/tmp/carbon108-sh-tools-182WJHDCJH74647-installer
sh_tools_zip=$tmp_dir/sh-tools-$SHTOOLS_VERSION.zip

cmd_list="curl-cvetest
          curl-exists
          curl-github
          curl-tini"

mkdir -p "$SHTOOLS_DIR" &&\
    mkdir -p "$tmp_dir" &&\
    curl -Lk $sh_tools_url --output $sh_tools_zip &&\
    unzip -o -q $sh_tools_zip -d "$tmp_dir" &&\
    for cmd in $cmd_list
        do
        cp $tmp_dir/sh-tools-$SHTOOLS_VERSION/$cmd $SHTOOLS_DIR
        done

rm -rf $tmp_dir
