#!/bin/bash

SHTOOLS_VERSION=${1:-20.3}
SHTOOLS_DIR=${2:-"/opt/sh-tools"}

sh_tools_url=https://github.com/carbon108/sh-tools-docker/archive/$SHTOOLS_VERSION.zip

tmp_dir=/tmp/carbon108-sh-tools-182WJHDCJH74647-installer
sh_tools_zip=$tmp_dir/sh-tools-$SHTOOLS_VERSION.zip

saved_dir=$PWD

function cmd_exists(){
command_name=$1
! command -v "$command_name" > /dev/null &&\
        echo "'$command_name' not found" &&\
        return 1
return 0
}

cmd_exists curl || exit 1
cmd_exists unzip || exit 1
cmd_exists shopt || exit 1

mkdir -p "$SHTOOLS_DIR" || exit 1
mkdir -p "$tmp_dir"

curl -L# $sh_tools_url --output $sh_tools_zip &&\
    unzip -o -q $sh_tools_zip -d "$tmp_dir"
cd $tmp_dir/sh-tools-$SHTOOLS_VERSION || exit 1

# Copy scripts omitting Git repo extra files
shopt -s extglob
cp -r !(tests|install-sh-tools) $SHTOOLS_DIR
    # should omit non-production files
shopt -u extglob

rm -rf $tmp_dir
cd $saved_dir || exit 1
