#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
PATH=$SCRIPT_DIR:$PATH

cmd-exists pipenv || exit 1

for pkg in "${@}"
do
    pipenv --version
    pipenv install "$pkg"
done

pipenv --version
pipenv install --system --dev --clear
