#!/bin/bash

SCRIPT_DIR=$(dirname "$0")
PATH=$SCRIPT_DIR:$PATH

cmd-exists pip || exit 1
cmd-exists pipenv || exit 1

for pkg in "${@}"
do
    pipenv install "$pkg"
done

pipenv install --system --dev --clear