#!/bin/sh

curl_github(){

local repo_path=$1
local release_tag=$2
local download_dir=$3
local file_list=${@:4}

[[ -z $file_list ]] &&\
    return 1

local repo_name=${repo_path##*/}
local release_trim=${release_tag#"${release_tag%%[0-9.-]*}"}
    # Reason: Relese arcvhives in GitHub use trimmed release tags, non-digits seem to be removed
    #         from tag prefix
    # HOWTO: https://unix.stackexchange.com/a/167766/203709

local zip_name=${repo_path//\//_}_${release_tag}
local zip_dir=/tmp/${zip_name}
local zip_file=${zip_dir}/${zip_name}.zip

mkdir -p $zip_dir
mkdir -p $download_dir
curl -Lk https://github.com/${repo_path}/archive/${release_tag}.zip --output ${zip_file}
unzip -o -q "${zip_file}" -d "${zip_dir}"

for f in ${file_list}
do
  cp "${zip_dir}/$repo_name-$release_trim/$f" "$download_dir"
done

}

