#!/bin/sh

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")

PATH=$src_dir:$PATH

printf "\nTest curl_exists works on google.com..."

! curl-exists "https://google.com/" &&\
    printf "\nTest fail: Can not curl google.com/\n"  &&\
    exit 1

curl-exists "https://google.com/QKJDGHscdsQKJshd"  &&\
    printf "\nTest fail: False positive response from google.com/\n" &&\
    exit 1

printf " ...OK\n"
