#!/bin/sh

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")
download_dir=$tests_dir/curl-tini-out-$(date +%s)

PATH=$src_dir:$PATH

printf "\nTest curl-tini gets tini binary..."

curl-tini $download_dir
! [[ -x "$download_dir/tini" ]] &&\
    printf "\nTest fail: File 'tini' not found or is not executable\n" &&\
    exit 1

rm -rf "$download_dir"

printf " ...OK\n"
