#!/bin/bash

call_tester(){

local tests_dir=$(dirname "$0")
local src_dir=$(dirname "$tests_dir")

source $src_dir/sh-tools-rc

printf "\nCurrent directory: $PWD\n"

cd $tests_dir

local download_dir=$PWD/test_sh-tools-output-3sc8dc45

local out_file=$download_dir/$src_file

curl_github 'krallin/tini' 'v0.18.0' $download_dir "ddist.sh src/tini.c"

! [[ -f "$download_dir/ddist.sh" ]] &&\
    printf "\nTest fail: File 'ddist.sh' Not found\n" &&\
    return 1

! [[ -f "$download_dir/tini.c" ]] &&\
    printf "\nTest fail: File 'tini.c' Not found\n" &&\
    return 1

rm -rf "$download_dir"

}

call_tester