#!/bin/bash

call_tester(){

local tests_dir=$(dirname "$0")
local src_dir=$(dirname "$tests_dir")

source $src_dir/sh-tools-rc

printf "\nCurrent directory: $PWD\n"

cd $tests_dir || return 1

local download_dir=$PWD/test_sh-tools-output-$(date +%s)

curl_github 'krallin/tini' 'v0.18.0' $download_dir ddist.sh src/tini.c

! [[ -f "$download_dir/ddist.sh" ]] &&\
    printf "\nTest fail: File 'ddist.sh' Not found\n"

! [[ -f "$download_dir/tini.c" ]] &&\
    printf "\nTest fail: File 'tini.c' Not found\n"

rm -rf "$download_dir"

}

call_tester