#!/bin/bash

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")

fixture_dir=$tests_dir/apt-get-add-fixture

PATH=$fixture_dir:$src_dir:$PATH

printf "\nCheck below that 'apt-get-add curl zip' maps to proper commands...\n\n"

apt-get-add curl zip

