#!/bin/bash

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")

download_dir=$tests_dir/test_install-sh-tools-out-$(date +%s)

PATH=$tests_dir:$src_dir:$PATH

printf "\nRunning tests...
Current directory: $PWD\n"

printf "\nTest 'install-sh-tools' gets scripts...\n\n"
install-sh-tools "0.1.5" "$download_dir"

cmd_list="curl-cvetest
          curl-exists
          curl-github
          curl-tini"

for cmd in $cmd_list
  do
    ! [[ -x "$download_dir/$cmd" ]] &&\
        printf "\nTest fail: File '$cmd' not found or is not executable\n" &&\
            exit 1
  done
rm -rf "$download_dir"

printf "\n...OK\n"