#!/bin/bash

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")
PATH=$tests_dir:$PATH
    # src dir should NOT be on the PATH as all those tools are
    # to be installed by this script

download_dir=$tests_dir/test_install-sh-tools-out-$(date +%s)

printf "\nRunning tests...
Current directory: $PWD\n"

printf "\nTest 'install-sh-tools' gets 3x scripts...\n\n"

$src_dir/install-sh-tools 0.1.6 ${download_dir}

cmd_list="apt-get-add
          curl-exists
          curl-tini"

for cmd in $cmd_list
  do
    ! [[ -x "$download_dir/$cmd" ]] &&\
        printf "\nTest fail: File '$cmd' not found or is not executable\n" &&\
            exit 1
  done
rm -rf "$download_dir"

printf "\n...OK\n"