#!/bin/bash

tests_dir=$(dirname "$0")
src_dir=$(dirname "$tests_dir")

download_dir=$tests_dir/test_install-sh-tools-out-$(date +%s)

PATH=$tests_dir:$src_dir:$PATH

printf "\nRunning tests...
Current directory: $PWD\n"

printf "\nTest installer gets sh-tools scripts...\n\n"

install-sh-tools "0.1.4" "$download_dir"

cmd_list="curl-exists
          curl-tini"

for cmd in $cmd_list
  do
    ! [[ -x "$download_dir/$cmd" ]] &&\
        printf "\nTest fail: File '$cmd' not found or is not executable\n" &&\
            exit 1
  done

rm -rf "$download_dir"
printf "\nInstaller test returned OK\n"